name: Build Kernel

on:
  push:
    branches: 
      - '**'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - '**'   # Matches all branches
    paths-ignore:
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Kernel
      uses: mlm-games/simple-kernel-build-action@main
      with:
        KERNEL_CONFIG: 'blossom_defconfig'
        ARCH: 'arm64'
        TOOLCHAIN_CLONE_CMD: 'mkdir -p $HOME/clang && wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r530567.tar.gz -O clang.tar.gz && tar xf clang.tar.gz -C $HOME/clang && sudo apt install gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi'
        ENABLE_CCACHE: 'true'
        MAKE_ARGS: 'O=out PATH=$HOME/clang/bin:$PATH CC="ccache clang" CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-'
        ENABLE_KSU: true
        KSU_KPROBE_ONLY: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build
        path: 'kernel_source/*.zip'
